# Generated by Django 3.2 on 2023-06-03 00:05

from django.db import migrations
import csv


def add_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    with open('./data/ingredients.csv', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            Ingredient.objects.create(
                name=row['name'],
                measurement_unit=row['measurement_unit']
            )


def remove_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    with open('./data/ingredients.csv', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            Ingredient.objects.filter(name=row['name']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.RunPython(
            add_ingredients,
            remove_ingredients
        )
    ]
